# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77000e5cdab7721b1ae20520771486b516d188cb8f4c14e4f6485327e389f91d2f0de07b4c5d89d72b3f571c14cd003fdb446d5980d7097d4c0413b19ea1adb3

test:
  secret_key_base: da8cf5f247bdb4b774f1bbe717257ea20c3242a133abed285ad7caed903b9865f6dba8194d799140adb87be09ffad15e98c9ac4adf12ab97defd4c205614971e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
